### ISSUE TITLE
Test Fail:   Capybara::Session with akephalos driver slow ajax load should wait for ajax to load

### ISSUE THREAD

**Issue by Nerian** [Nerian/akephalos2#10]
```
10) Capybara::Session with akephalos driver slow ajax load should wait for ajax to load
   Failure/Error: @session.visit('/slow_ajax_load')
   NativeException:
     com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "$" is not defined. (script in http://127.0.0.1:51146/slow_ajax_load from (5, 36) to (12, 14)#6)
```
